<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'branchtest' => '/BranchTest.php',
                'dailytodolisttest' => '/DailyToDoListTest.php',
                'durationtest' => '/DurationTest.php',
                'lottest' => '/LotTest.php',
                'numberofcarstest' => '/NumberOfCarsTest.php',
                'reservationtest' => '/ReservationTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
