<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'arneslot' => '/ArnesLot.php',
                'branch' => '/Branch.php',
                'dailytodolist' => '/DailyToDoList.php',
                'duration' => '/Duration.php',
                'goodlot' => '/GoodLot.php',
                'lot' => '/Lot.php',
                'numberofvehicles' => '/NumberOfVehicles.php',
                'reservation' => '/Reservation.php',
                'todolisthtmlrenderer' => '/ToDoListHtmlRenderer.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
